language: cpp

before_install:
  - sudo apt-add-repository ppa:wpilib/toolchain -y
  - sudo apt-get -qq update
  - sudo apt-get install -y frc-toolchain
  - wget http://www.filehosting.org/file/details/640469/wpilib.zip
  - unzip wpilib.zip
  - mv wpilib/ ~

script: make